<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="1" time="25972">
 <testsuite name="Sync1 Login Accessibility Validations" timestamp="2019-08-28T04:00:20" hostname="localhost" time="25.972" errors="0" tests="1" skipped="0" disabled="0" failures="1">
  <testcase classname="Sync1 Login Accessibility Validations" name="Accessibility Tests are passing using loan.officer user" time="21.488">
   <failure type="toEqual" message="Expected &apos;Axe violations: 2 on Login page&apos; to equal &apos;Axe violations: 0 on Login page&apos;."><![CDATA[Error: Failed expectation
    at C:\Users\eduardo\Desktop\DemoAxe\e2e\common\app.cmm.sync1UiAccessibility.ts:24:29
    at ManagedPromise.invokeCallback_ (C:\Users\eduardo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\eduardo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\eduardo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\eduardo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\eduardo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>